ALTER TABLE workspaces ADD COLUMN template_secrets_json TEXT NOT NULL DEFAULT '{}';

-- Remove secrets generated by the superseded implicit VNC credential behavior.
UPDATE workspaces SET vnc_password = '';
